
services:
  - type: web
    name: telegram-ai-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: TELEGRAM_BOT_TOKEN
